name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Здесь укажите вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu
    
    steps:
      - name: Copy default.conf via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "/*"
          target: "/home/root/"
          strip_components: 2

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Server
        run: |
          ls
          pwd
          go build
          ./go-htmx-tables

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Добавьте ваш приватный SSH-ключ в настройках репозитория
